Persist discord session
still-pursuing/paper-trader pull request #20
Opened 2022-09-01 22:21 UTC by samau3

2022-09-07 03:18 UTC, li-andy commented on app/src/App.tsx
> +					let decodedToken = decodeToken<string>(token);
I thought we decided not to decode the JWT on the client?

2022-09-07 03:18 UTC, li-andy commented on app/src/App.tsx
> +	console.debug("App", { token, currentUser, searchParams })
remove?

2022-09-07 03:19 UTC, li-andy commented on app/src/App.tsx
> +					console.error("Can't load user", err);
would we want to throw this too low the error above?

2022-09-07 03:19 UTC, li-andy commented on app/src/App.tsx
> +		console.log('In App effect')
remove?

2022-09-07 03:20 UTC, li-andy commented on app/src/App.tsx
> +				if (localStorage['stateString'] !== searchParams.get('state')) {
indentation looks massive here, might be some formatter issues

2022-09-07 03:20 UTC, li-andy commented on app/src/App.tsx
> +				if (localStorage['stateString'] !== searchParams.get('state')) {
oh, actually it's everywhere 🤔

2022-09-07 03:23 UTC, li-andy commented on app/src/App.tsx
> +	)
`handleLogin()` and much of the `useEffect` feel like they could be abstracted out of this file. 

I didn't even realize we were in the App file until I saw the routes

2022-09-07 03:24 UTC, li-andy commented on app/src/config.ts
you can just export variables individually

2022-09-07 03:26 UTC, li-andy commented on server/middleware/auth.ts
> +            const token = authHeader.replace(/^[Bb]earer /, "").trim();
a simpler option may to just split on the space if we always expect `Bearer[_]` to prefix the token

2022-09-07 03:27 UTC, li-andy commented on server/middleware/auth.ts
> +        return next();
can we scope this `catch` down any more?

2022-09-07 03:28 UTC, li-andy commented on server/src/config.ts
> +const SECRET_KEY = process.env.SECRET_KEY || "secret-dev";
can we make this something more specific?

2022-09-07 03:30 UTC, li-andy commented
A couple questions + stray console statements, but good first cut!

2022-09-07 03:35 UTC, samau3 commented on server/src/config.ts
> +const SECRET_KEY = process.env.SECRET_KEY || "secret-dev";
SECRET_KEY will be a more complicated variable in production, but for development purposes isn't a simple key sufficient?

2022-09-07 03:38 UTC, samau3 commented on app/src/App.tsx
> +				if (localStorage['stateString'] !== searchParams.get('state')) {
I did have a formatter error when I accidentally changed the default spacing but trying to undo didn't change it back, I plan to submit a new PR after that will have every file utilize spacing of 2 instead of 4

2022-09-07 03:39 UTC, li-andy commented on app/src/App.tsx
> +				if (localStorage['stateString'] !== searchParams.get('state')) {
I think it's at 8 right now

2022-09-07 03:39 UTC, li-andy commented on app/src/App.tsx
> +				if (localStorage['stateString'] !== searchParams.get('state')) {
also as a warning, submitting a PR like that could overwrite the git blame history if you don't explicitly exclude the commit from blame

2022-09-07 03:40 UTC, li-andy commented on server/src/config.ts
> +const SECRET_KEY = process.env.SECRET_KEY || "secret-dev";
mb, meant the name of the variable itself

2022-09-07 03:53 UTC, samau3 commented on app/src/App.tsx
> +				if (localStorage['stateString'] !== searchParams.get('state')) {
The formatting error was VS Code when I adjusted the Tab Size number, but the formatting showing up here doesn't match the formatting on VS Code. Not quite sure what's causing the difference, but I'll try adjusting it in a new commit later.

Ah then will reach out about how to best handle changing the formatting of the files later on.

2022-09-08 04:41 UTC, li-andy commented on app/src/App.tsx
> +					console.error("Can't load user", err);
- it's nice that you have if/elses providing coverage for different cases
- but it's important to consider how a user could end up in a specific case
- in this case, this would be an unhappy path where a user _had_ a token but it was unreadable by your client, likely due to tampering
- in this situation you should consider reasonable ways to handle the error, eg. redirecting them back to the login page

2022-09-09 18:25 UTC, li-andy commented on app/package.json
> +    "react-jwt": "^1.1.6",
```suggestion
```

2022-09-09 18:26 UTC, li-andy commented on app/src/App.tsx
> +	const [currentUser, setCurrentUser] = useState<UserData | null>(null);
```suggestion
	const [currentUser, setCurrentUser] = useState<UserData>(null);
```
this is the same as the above

2022-09-09 18:27 UTC, li-andy commented on app/src/UserContext.ts
> +const UserContext = createContext<UserContextInterface | null>(null);
```suggestion
const UserContext = createContext<UserContextInterface>(null);
```
don't need the extra `null` here

2022-09-09 18:33 UTC, li-andy commented on app/src/helpers/Api.ts
> +    static generateRandomString() {
instead of rolling out own random string generator, can we use something like UUID.v4?

2022-09-09 18:43 UTC, li-andy commented on app/src/helpers/UserSession.ts
> +				setToken(token);
why pass setToken as a callback instead of calling it on the returned value from the calling function?

2022-09-09 18:52 UTC, li-andy commented on server/helpers/token.ts
> +export default createToken;
```suggestion
export function createToken(user: string) {

    const payload = {
        username: user
    };

    return jwt.sign(payload, JWT_SECRET_KEY);
}
```

you can just export the function directly instead of `export default`

2022-09-09 18:52 UTC, li-andy commented on server/helpers/token.ts
> +export default createToken;
you'll need to update your calling functions to `import { createToken }` though (which is clearer IMO)

2022-09-09 18:53 UTC, li-andy requested changes
almost there!

2022-09-09 18:57 UTC, samau3 commented on app/src/App.tsx
> +	const [currentUser, setCurrentUser] = useState<UserData | null>(null);
Since the initial state is `null`, need to use `| null` or else there will be a type assignment error. Similar to this [discussion](https://stackoverflow.com/a/59126275)

2022-09-09 19:10 UTC, li-andy commented on app/src/App.tsx
> +	const [currentUser, setCurrentUser] = useState<UserData | null>(null);
https://stackoverflow.com/a/61823158/7995306
it's already implied by the unitialized state without specifying in the `<>`

also, `undefined` may be preferred here instead of `null`

2022-09-09 19:11 UTC, samau3 commented on app/src/helpers/Api.ts
> +class PaperTraderApi {
Renamed file to match the class

2022-09-09 19:11 UTC, samau3 commented on app/package.json
> +    "react-jwt": "^1.1.6",
Removed package

2022-09-09 21:38 UTC, samau3 commented on app/src/App.tsx
> +	const [currentUser, setCurrentUser] = useState<UserData | null>(null);
Made the change to use undefined instead of null

2022-09-09 21:44 UTC, samau3 commented on app/src/helpers/UserSession.ts
> +				setToken(token);
I made this change to reduce the size of handleLogin, but this may have moved too much out of the App component.

Are you suggesting `UserData.login()` to return token? So inside `handleLogin` it has: 
`
setToken(UserData.login(searchParams);
localStorage.setItem('userToken', token);
`

2022-09-09 23:50 UTC, li-andy commented on app/src/helpers/UserSession.ts
> +				setToken(token);
yup

2022-09-10 08:10 UTC, li-andy commented on app/src/pages/Login/index.tsx
> +    const encodedToken = encodeURIComponent(`${localStorage.getItem('stateString')}`) // localStorage.getItem can return null, but encodeURIComponent does not accept type null
nit: assert that getItem() is not null a line before

2022-09-10 08:12 UTC, li-andy approved these changes
minor comment

2022-09-11 11:02 UTC, li-andy commented on app/src/pages/Login/index.tsx
> +    // todo: add an else statement to handle null stateString?
should you just create a stateString in this case?

2022-09-11 11:03 UTC, li-andy commented on app/src/pages/Login/index.tsx
> +    const storedStateString = localStorage.getItem('stateString');
is this used exclusively for CSRF? consider renaming to something more specific—"state" may be ambiguous if this code is viewed far in the future

2022-09-12 04:19 UTC, samau3 commented on app/src/pages/Login/index.tsx
> +    const storedStateString = localStorage.getItem('stateString');
Renamed to csrfStateString incase "state" is used for something else in the future and to better define the purpose of the string

2022-09-12 04:27 UTC, samau3 commented on app/src/pages/Login/index.tsx
> +    // todo: add an else statement to handle null stateString?
Ah good point; added call to generate the CSRF string and call the getDiscordOAuthCode function again

2022-09-12 05:04 UTC, li-andy approved these changes

2022-09-12 05:05 UTC, li-andy commented
🚀

2022-09-12 05:10 UTC, merged